
library( LCTMtools )
library(readxl)
library( lcmm )
library(knitr)

data_df <- read_excel("long_melt_epds.xlsx")
data_df <-data_df[c(2:4)]
data_df$value <-data_df$value+1
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T0'] <- 3
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T1'] <- 6
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T2'] <- 9
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T3'] <- 12
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T4'] <- 15

data_df$EPDS <- as.numeric(data_df$EPDS)
data_df$index <- as.integer(data_df$index)
data_df$value <- as.integer(data_df$value)
m02tf_nr <- lcmm(fixed = value~1,
            mixture = ~ 1,
            random = ~ 1,
            ng = 2, nwg=TRUE,
            idiag = FALSE, 
            data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                 
                                                                 random = ~ 1,
                                                                 ng = 1, 
                                                                 idiag = FALSE, 
                                                                 data = data.frame(data_df), subject = "index")) 
m02tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 2, nwg=TRUE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                  random = ~ 1,
                                  ng = 1, 
                                  idiag = FALSE, 
                                  data = data.frame(data_df), subject = "index"))


m02ff_nr <- lcmm(fixed = value~1,
              mixture = ~ 1,
              random = ~ 1,
              ng = 2, nwg=FALSE,
              idiag = FALSE, 
              data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                   
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
m02ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                            mixture = ~ 1,
                                            random = ~ 1,
                                            ng = 2, nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))



m02ft_nr <- lcmm(fixed = value~1,
              mixture = ~ 1,
              random = ~ 1,
              ng = 2, nwg=FALSE,
              idiag = TRUE, 
              data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                   
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, data = data.frame(data_df), subject = "index"))

m02ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                                                                                          mixture = ~ 1,
                                                                                                          random = ~ 1,
                                                                                                          ng = 2, nwg=FALSE,
                                                                                                          idiag = TRUE, 
                                                                                                          data = data.frame(data_df), subject = "index"),
                                                                                                     rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                                                                                     random = ~ 1,
                                                                                                                                     ng = 1, 
                                                                                                                                     idiag = TRUE, 
                                                                                                                                     data = data.frame(data_df), subject = "index"))
m02tt_nr <- lcmm(fixed = value~1,
              mixture = ~ 1,
              random = ~ 1,
              ng = 2, nwg=TRUE,
              idiag = TRUE, 
              data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 
m02tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 2, nwg=TRUE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))

mLF2tf_nr <- lcmm(fixed = value~1+EPDS,
             mixture = ~ 1,
             random = ~ 1,
             ng = 2,nwg=TRUE,
             idiag = FALSE, 
             data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index")) 
mLF2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                mixture = ~ 1,
                random = ~ 1,
                ng = 2,nwg=TRUE,
                idiag = FALSE, 
                data = data.frame(data_df), subject = "index"),
                rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                     random = ~ 1,
                                                                     ng = 1, 
                                                                     idiag = FALSE, 
                                                                     data = data.frame(data_df), subject = "index")) 
mLF2ff_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=FALSE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=FALSE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF2ft_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=FALSE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=FALSE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF2tt_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=TRUE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=TRUE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 

mLFR2tf_nr <- lcmm(fixed = value~1+EPDS,
              mixture = ~ 1,
              random = ~ 1+EPDS,
              ng = 2,nwg=TRUE,
              idiag = FALSE, 
              data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1,
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFR2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 2,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1+EPDS,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLFR2ff_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 2,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 2,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR2ft_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 2,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 2,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR2tt_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 2,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 2,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 



mLFM2tf_nr <- lcmm(fixed = value~1+EPDS,
              mixture = ~ 1+EPDS,
              random = ~ 1,
              ng = 2,nwg=TRUE,
              idiag = FALSE, 
              data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1,
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index"))

mLFM2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 2,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFM2ff_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 2,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 2,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM2ft_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 2,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 2,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM2tt_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 2,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 2,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 


mLFRM2tf_nr <- lcmm(fixed = value~1+EPDS,
               mixture = ~ 1+EPDS,
               random = ~ 1+EPDS,
               ng = 2,nwg=TRUE,
               idiag = FALSE, 
               data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                     random = ~ 1+EPDS,
                                                                     ng = 1,
                                                                     idiag = FALSE, 
                                                                     data = data.frame(data_df), subject = "index")) 
mLFRM2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM2ff_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM2ft_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM2tt_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 


mQF2tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
             mixture = ~ 1,
             random = ~ 1,
             ng = 2,
             idiag = FALSE, 
             data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                  random = ~ 1,
                                                                  ng = 1,
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index") )
mQF2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF2ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )
mQF2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = FALSE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQF2ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )

mQF2tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQFLR2tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
               mixture = ~ 1,
               random = ~ 1+EPDS,
               ng = 2,nwg=TRUE,
               idiag = FALSE, 
               data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                     random = ~ 1+EPDS,ng = 1,
                                                                     idiag = FALSE, 
                                                                     data = data.frame(data_df), subject = "index") )

mQFLR2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR2ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFLR2ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR2tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFQR2tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
               mixture = ~ 1,
               random = ~ 1+EPDS+I(EPDS^2),
               ng = 2,nwg=TRUE,
               idiag = FALSE, 
               data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                    random = ~ 1+EPDS+I(EPDS^2),
                                                                    ng = 1,
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 


mQFQR2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 



mQFQR2ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index")) 
mQFQR2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR2ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR2tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM2tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
               mixture = ~ 1+EPDS+I(EPDS^2),
               random = ~ 1,
               ng = 2,nwg=TRUE,
               idiag = FALSE, 
               data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                    random = ~ 1,
                                                                    ng = 1,
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mQFQM2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQM2ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM2ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM2tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQMLR2tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                 mixture = ~ 1+EPDS+I(EPDS^2),
                 random = ~ 1+EPDS,
                 ng = 2,nwg=TRUE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1+EPDS,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 

mQFQMLR2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1+EPDS,
                                          ng = 2,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 


mQFQMLR2ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 2,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 2,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 




mQFQMLR2ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 2,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 2,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR2tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 2,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 2,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))
 
mQFQMQR2tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                 mixture = ~ 1+EPDS+I(EPDS^2),
                 random = ~ 1+EPDS+I(EPDS^2),
                 ng = 2,nwg=TRUE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                        random = ~ 1+EPDS+I(EPDS^2),
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mQFQMQR2tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 2,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))


mQFQMQR2ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 2,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR2ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 2,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))

mQFQMQR2ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 2,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR2ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 2,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR2tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 2,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))


mQFQMQR2tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 2,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

summarytable(m02tf_nr,m02tf_nr_gridsearch,m02ff_nr,m02ff_nr_gridsearch,m02ft_nr,m02ft_nr_gridsearch,m02tt_nr,m02tt_nr_gridsearch,
             mLF2tf_nr,mLF2tf_nr_gridsearch,mLF2ff_nr,mLF2ff_nr_gridsearch,mLF2ft_nr,mLF2ft_nr_gridsearch,mLF2tt_nr,mLF2tt_nr_gridsearch,
             mLFR2tf_nr,mLFR2tf_nr_gridsearch,mLFR2ff_nr,mLFR2ff_nr_gridsearch,mLFR2ft_nr,mLFR2ft_nr_gridsearch,mLFR2tt_nr,mLFR2tt_nr_gridsearch,
             mLFM2tf_nr,mLFM2tf_nr_gridsearch,mLFM2ff_nr,mLFM2ff_nr_gridsearch,mLFM2ft_nr,mLFM2ft_nr_gridsearch,mLFM2tt_nr,mLFM2tt_nr_gridsearch,
             mLFRM2tf_nr,mLFRM2tf_nr_gridsearch,mLFRM2ff_nr,mLFRM2ff_nr_gridsearch,mLFRM2ft_nr,mLFRM2ft_nr_gridsearch,mLFRM2tt_nr,mLFRM2tt_nr_gridsearch,
             mQF2tf_nr,mQF2tf_nr_gridsearch,mQF2ff_nr,mQF2ff_nr_gridsearch,mQF2ft_nr,mQF2ft_nr_gridsearch,mQF2tt_nr,mQF2tt_nr_gridsearch,
             mQFLR2tf_nr,mQFLR2tf_nr_gridsearch,mQFLR2ff_nr,mQFLR2ff_nr_gridsearch,mQFLR2ft_nr,mQFLR2ft_nr_gridsearch,mQFLR2tt_nr,mQFLR2tt_nr_gridsearch,
             mQFQR2tf_nr,mQFQR2tf_nr_gridsearch,mQFQR2ff_nr,mQFQR2ff_nr_gridsearch,mQFQR2ft_nr,mQFQR2ft_nr_gridsearch,mQFQR2tt_nr,mQFQR2tt_nr_gridsearch,
             mQFQM2tf_nr,mQFQM2tf_nr_gridsearch,mQFQM2ff_nr,mQFQM2ff_nr_gridsearch,mQFQM2ft_nr,mQFQM2ft_nr_gridsearch,mQFQM2tt_nr,mQFQM2tt_nr_gridsearch,
             mQFQMLR2tf_nr,mQFQMLR2tf_nr_gridsearch,mQFQMLR2ff_nr,mQFQMLR2ff_nr_gridsearch,mQFQMLR2ft_nr,mQFQMLR2ft_nr_gridsearch,mQFQMLR2tt_nr,mQFQMLR2tt_nr_gridsearch,
             mQFQMQR2tf_nr,mQFQMQR2tf_nr_gridsearch,mQFQMQR2ff_nr,mQFQMQR2ff_nr_gridsearch,mQFQMQR2ft_nr,mQFQMQR2ft_nr_gridsearch,mQFQMQR2tt_nr,mQFQMQR2tt_nr_gridsearch, 
             which = c("G", "loglik", "conv", "npm", "AIC", "BIC", "SABIC", "entropy", "%class"))->t2
kable(t2, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  cat(., file = "m2_lcmm.html")
