
library( LCTMtools )
library(readxl)
library( lcmm )
library(knitr)

data_df <- read_excel("long_melt_epds.xlsx")
data_df <-data_df[c(2:4)]
data_df$value <-data_df$value+1
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T0'] <- 3
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T1'] <- 6
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T2'] <- 9
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T3'] <- 12
data_df$"EPDS"[data_df$"EPDS"=='EPDS_T4'] <- 15

data_df$EPDS <- as.numeric(data_df$EPDS)
data_df$index <- as.integer(data_df$index)
data_df$value <- as.integer(data_df$value)

m04tf_nr <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 4, nwg=TRUE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = FALSE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m04tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 4, nwg=TRUE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))


m04ff_nr <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 4, nwg=FALSE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = FALSE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m04ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 4, nwg=FALSE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))



m04ft_nr <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 4, nwg=FALSE,
                 idiag = TRUE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = TRUE, data = data.frame(data_df), subject = "index"))

m04ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 4, nwg=FALSE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))
m04tt_nr <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 4, nwg=TRUE,
                 idiag = TRUE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = TRUE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m04tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 4, nwg=TRUE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))

mLF4tf_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,nwg=TRUE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,nwg=TRUE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF4ff_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,nwg=FALSE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,nwg=FALSE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF4ft_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,nwg=FALSE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,nwg=FALSE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF4tt_nr <- lcmm(fixed = value~1+EPDS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,nwg=TRUE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,nwg=TRUE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 

mLFR4tf_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 4,nwg=TRUE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 4,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFR4ff_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 4,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 4,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR4ft_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 4,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 4,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR4tt_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1,
                   random = ~ 1+EPDS,
                   ng = 4,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+EPDS,
                                                                         random = ~ 1+EPDS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1,
                                         random = ~ 1+EPDS,
                                         ng = 4,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1+EPDS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 



mLFM4tf_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 4,nwg=TRUE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 4,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFM4ff_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 4,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 4,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM4ft_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 4,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 4,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM4tt_nr <- lcmm(fixed = value~1+EPDS,
                   mixture = ~ 1+EPDS,
                   random = ~ 1,
                   ng = 4,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                         mixture = ~ 1+EPDS,
                                         random = ~ 1,
                                         ng = 4,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 


mLFRM4tf_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM4ff_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM4ft_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM4tt_nr <- lcmm(fixed = value~1+EPDS,
                    mixture = ~ 1+EPDS,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS,
                                                                          random = ~ 1+EPDS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS,
                                          mixture = ~ 1+EPDS,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS,
                                                                                                                          random = ~ 1+EPDS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 


mQF4tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )
mQF4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = FALSE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )

mQF4ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )
mQF4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = FALSE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQF4ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )

mQF4tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 4,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 4,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQFLR4tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR4ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFLR4ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR4tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS,
                    ng = 4,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                          random = ~ 1+EPDS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS,
                                          ng = 4,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                           random = ~ 1+EPDS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFQR4tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 4,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 


mQFQR4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 4,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQR4ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 4,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mQFQR4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 4,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR4ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 4,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 4,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR4tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1,
                    random = ~ 1+EPDS+I(EPDS^2),
                    ng = 4,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1+EPDS+I(EPDS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+EPDS+I(EPDS^2),
                                          ng = 4,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM4tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 4,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 4,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQM4ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 4,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 4,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM4ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 4,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 4,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM4tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                    mixture = ~ 1+EPDS+I(EPDS^2),
                    random = ~ 1,
                    ng = 4,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                          mixture = ~ 1+EPDS+I(EPDS^2),
                                          random = ~ 1,
                                          ng = 4,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQMLR4tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 4,nwg=TRUE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 

mQFQMLR4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 4,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR4ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 4,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 4,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 




mQFQMLR4ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 4,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 4,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR4tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS,
                      ng = 4,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                            random = ~ 1+EPDS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS,
                                            ng = 4,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR4tf_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 4,nwg=TRUE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR4tf_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 4,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))


mQFQMQR4ff_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 4,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR4ff_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 4,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))

mQFQMQR4ft_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 4,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR4ft_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 4,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR4tt_nr <- lcmm(fixed = value~1+EPDS+I(EPDS^2),
                      mixture = ~ 1+EPDS+I(EPDS^2),
                      random = ~ 1+EPDS+I(EPDS^2),
                      ng = 4,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                             random = ~ 1+EPDS+I(EPDS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))


mQFQMQR4tt_nr_gridsearch <- gridsearch(lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                            mixture = ~ 1+EPDS+I(EPDS^2),
                                            random = ~ 1+EPDS+I(EPDS^2),
                                            ng = 4,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+EPDS+I(EPDS^2),
                                                                                                                            random = ~ 1+EPDS+I(EPDS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

summarytable(m04tf_nr,m04tf_nr_gridsearch,m04ff_nr,m04ff_nr_gridsearch,m04ft_nr,m04ft_nr_gridsearch,m04tt_nr,m04tt_nr_gridsearch,
             mLF4tf_nr,mLF4tf_nr_gridsearch,mLF4ff_nr,mLF4ff_nr_gridsearch,mLF4ft_nr,mLF4ft_nr_gridsearch,mLF4tt_nr,mLF4tt_nr_gridsearch,
             mLFR4tf_nr,mLFR4tf_nr_gridsearch,mLFR4ff_nr,mLFR4ff_nr_gridsearch,mLFR4ft_nr,mLFR4ft_nr_gridsearch,mLFR4tt_nr,mLFR4tt_nr_gridsearch,
             mLFM4tf_nr,mLFM4tf_nr_gridsearch,mLFM4ff_nr,mLFM4ff_nr_gridsearch,mLFM4ft_nr,mLFM4ft_nr_gridsearch,mLFM4tt_nr,mLFM4tt_nr_gridsearch,
             mLFRM4tf_nr,mLFRM4tf_nr_gridsearch,mLFRM4ff_nr,mLFRM4ff_nr_gridsearch,mLFRM4ft_nr,mLFRM4ft_nr_gridsearch,mLFRM4tt_nr,mLFRM4tt_nr_gridsearch,
             mQF4tf_nr,mQF4tf_nr_gridsearch,mQF4ff_nr,mQF4ff_nr_gridsearch,mQF4ft_nr,mQF4ft_nr_gridsearch,mQF4tt_nr,mQF4tt_nr_gridsearch,
             mQFLR4tf_nr,mQFLR4tf_nr_gridsearch,mQFLR4ff_nr,mQFLR4ff_nr_gridsearch,mQFLR4ft_nr,mQFLR4ft_nr_gridsearch,mQFLR4tt_nr,mQFLR4tt_nr_gridsearch,
             mQFQR4tf_nr,mQFQR4tf_nr_gridsearch,mQFQR4ff_nr,mQFQR4ff_nr_gridsearch,mQFQR4ft_nr,mQFQR4ft_nr_gridsearch,mQFQR4tt_nr,mQFQR4tt_nr_gridsearch,
             mQFQM4tf_nr,mQFQM4tf_nr_gridsearch,mQFQM4ff_nr,mQFQM4ff_nr_gridsearch,mQFQM4ft_nr,mQFQM4ft_nr_gridsearch,mQFQM4tt_nr,mQFQM4tt_nr_gridsearch,
             mQFQMLR4tf_nr,mQFQMLR4tf_nr_gridsearch,mQFQMLR4ff_nr,mQFQMLR4ff_nr_gridsearch,mQFQMLR4ft_nr,mQFQMLR4ft_nr_gridsearch,mQFQMLR4tt_nr,mQFQMLR4tt_nr_gridsearch,
             mQFQMQR4tf_nr,mQFQMQR4tf_nr_gridsearch,mQFQMQR4ff_nr,mQFQMQR4ff_nr_gridsearch,mQFQMQR4ft_nr,mQFQMQR4ft_nr_gridsearch,mQFQMQR4tt_nr,mQFQMQR4tt_nr_gridsearch, 
             which = c("G", "loglik", "conv", "npm", "AIC", "BIC", "SABIC", "entropy", "%class"))->t4
kable(t4, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  cat(., file = "m4_lcmm.html")