library( LCTMtools )
library(readxl)

data_df <- read_excel("long_melt_mpas.xlsx")
data_df <-data_df[c(2:4)]
data_df$value <-data_df$value+1
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T1'] <- 6
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T2'] <- 9
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T3'] <- 12
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T4'] <- 15

data_df$MPAS <- as.numeric(data_df$MPAS)
data_df$index <- as.integer(data_df$index)
data_df$value <- as.integer(data_df$value)
m02tf_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 2, nwg=TRUE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = FALSE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m02tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 2, nwg=TRUE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))


m02ff_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 2, nwg=FALSE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = FALSE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m02ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 2, nwg=FALSE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))



m02ft_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 2, nwg=FALSE,
                 idiag = TRUE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = TRUE, data = data.frame(data_df), subject = "index"))

m02ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 2, nwg=FALSE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))
m02tt_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 2, nwg=TRUE,
                 idiag = TRUE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = TRUE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m02tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 2, nwg=TRUE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))

mLF2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=TRUE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=TRUE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=FALSE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=FALSE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=FALSE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=FALSE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,nwg=TRUE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,nwg=TRUE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 

mLFR2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 2,nwg=TRUE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 2,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFR2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 2,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 2,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 2,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 2,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 2,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 2,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 



mLFM2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 2,nwg=TRUE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 2,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFM2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 2,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 2,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 2,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 2,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 2,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 2,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 


mLFRM2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 


mQF2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )
mQF2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = FALSE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )

mQF2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )
mQF2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = FALSE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQF2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )

mQF2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 2,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 2,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQFLR2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFLR2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFQR2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 


mQFQR2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 2,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQR2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mQFQR2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 2,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQM2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 2,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 2,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 2,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 2,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQMLR2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 2,nwg=TRUE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 

mQFQMLR2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 2,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 2,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 2,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 




mQFQMLR2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 2,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 2,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 2,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 2,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR2tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 2,nwg=TRUE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR2tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 2,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))


mQFQMQR2ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 2,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR2ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 2,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))

mQFQMQR2ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 2,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR2ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 2,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR2tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 2,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))


mQFQMQR2tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 2,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

summarytable(m02tf_nr_MPAS,m02tf_nr_gridsearch_MPAS,m02ff_nr_MPAS,m02ff_nr_gridsearch_MPAS,m02ft_nr_MPAS,m02ft_nr_gridsearch_MPAS,m02tt_nr_MPAS,m02tt_nr_gridsearch_MPAS,
             mLF2tf_nr_MPAS,mLF2tf_nr_gridsearch_MPAS,mLF2ff_nr_MPAS,mLF2ff_nr_gridsearch_MPAS,mLF2ft_nr_MPAS,mLF2ft_nr_gridsearch_MPAS,mLF2tt_nr_MPAS,mLF2tt_nr_gridsearch_MPAS,
             mLFR2tf_nr_MPAS,mLFR2tf_nr_gridsearch_MPAS,mLFR2ff_nr_MPAS,mLFR2ff_nr_gridsearch_MPAS,mLFR2ft_nr_MPAS,mLFR2ft_nr_gridsearch_MPAS,mLFR2tt_nr_MPAS,mLFR2tt_nr_gridsearch_MPAS,
             mLFM2tf_nr_MPAS,mLFM2tf_nr_gridsearch_MPAS,mLFM2ff_nr_MPAS,mLFM2ff_nr_gridsearch_MPAS,mLFM2ft_nr_MPAS,mLFM2ft_nr_gridsearch_MPAS,mLFM2tt_nr_MPAS,mLFM2tt_nr_gridsearch_MPAS,
             mLFRM2tf_nr_MPAS,mLFRM2tf_nr_gridsearch_MPAS,mLFRM2ff_nr_MPAS,mLFRM2ff_nr_gridsearch_MPAS,mLFRM2ft_nr_MPAS,mLFRM2ft_nr_gridsearch_MPAS,mLFRM2tt_nr_MPAS,mLFRM2tt_nr_gridsearch_MPAS,
             mQF2tf_nr_MPAS,mQF2tf_nr_gridsearch_MPAS,mQF2ff_nr_MPAS,mQF2ff_nr_gridsearch_MPAS,mQF2ft_nr_MPAS,mQF2ft_nr_gridsearch_MPAS,mQF2tt_nr_MPAS,mQF2tt_nr_gridsearch_MPAS,
             mQFLR2tf_nr_MPAS,mQFLR2tf_nr_gridsearch_MPAS,mQFLR2ff_nr_MPAS,mQFLR2ff_nr_gridsearch_MPAS,mQFLR2ft_nr_MPAS,mQFLR2ft_nr_gridsearch_MPAS,mQFLR2tt_nr_MPAS,mQFLR2tt_nr_gridsearch_MPAS,
             mQFQR2tf_nr_MPAS,mQFQR2tf_nr_gridsearch_MPAS,mQFQR2ff_nr_MPAS,mQFQR2ff_nr_gridsearch_MPAS,mQFQR2ft_nr_MPAS,mQFQR2ft_nr_gridsearch_MPAS,mQFQR2tt_nr_MPAS,mQFQR2tt_nr_gridsearch_MPAS,
             mQFQM2tf_nr_MPAS,mQFQM2tf_nr_gridsearch_MPAS,mQFQM2ff_nr_MPAS,mQFQM2ff_nr_gridsearch_MPAS,mQFQM2ft_nr_MPAS,mQFQM2ft_nr_gridsearch_MPAS,mQFQM2tt_nr_MPAS,mQFQM2tt_nr_gridsearch_MPAS,
             mQFQMLR2tf_nr_MPAS,mQFQMLR2tf_nr_gridsearch_MPAS,mQFQMLR2ff_nr_MPAS,mQFQMLR2ff_nr_gridsearch_MPAS,mQFQMLR2ft_nr_MPAS,mQFQMLR2ft_nr_gridsearch_MPAS,mQFQMLR2tt_nr_MPAS,mQFQMLR2tt_nr_gridsearch_MPAS,
             mQFQMQR2tf_nr_MPAS,mQFQMQR2tf_nr_gridsearch_MPAS,mQFQMQR2ff_nr_MPAS,mQFQMQR2ff_nr_gridsearch_MPAS,mQFQMQR2ft_nr_MPAS,mQFQMQR2ft_nr_gridsearch_MPAS,mQFQMQR2tt_nr_MPAS,mQFQMQR2tt_nr_gridsearch_MPAS, 
             which = c("G", "loglik", "conv", "npm", "AIC", "BIC", "SABIC", "entropy", "%class"))->t2_MPAS
kable(t2_MPAS, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  cat(., file = "m2_MPAS.html")