library( LCTMtools )
library(readxl)

data_df <- read_excel("long_melt_mpas.xlsx")
data_df <-data_df[c(2:4)]
data_df$value <-data_df$value+1
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T1'] <- 6
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T2'] <- 9
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T3'] <- 12
data_df$"MPAS"[data_df$"MPAS"=='MPAS_T4'] <- 15

data_df$MPAS <- as.numeric(data_df$MPAS)
data_df$index <- as.integer(data_df$index)
data_df$value <- as.integer(data_df$value)

m03tf_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 3, nwg=TRUE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = FALSE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m03tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 3, nwg=TRUE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))


m03ff_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 3, nwg=FALSE,
                 idiag = FALSE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = FALSE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m03ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 3, nwg=FALSE,
                                       idiag = FALSE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = FALSE, 
                                                                  data = data.frame(data_df), subject = "index"))



m03ft_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 3, nwg=FALSE,
                 idiag = TRUE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = TRUE, data = data.frame(data_df), subject = "index"))

m03ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 3, nwg=FALSE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))
m03tt_nr_MPAS <- lcmm(fixed = value~1,
                 mixture = ~ 1,
                 random = ~ 1,
                 ng = 3, nwg=TRUE,
                 idiag = TRUE, 
                 data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1,
                                                                      random = ~ 1,
                                                                      ng = 1, 
                                                                      idiag = TRUE, 
                                                                      data = data.frame(data_df), subject = "index")) 
m03tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1,
                                       mixture = ~ 1,
                                       random = ~ 1,
                                       ng = 3, nwg=TRUE,
                                       idiag = TRUE, 
                                       data = data.frame(data_df), subject = "index"),
                                  rep=100, maxiter=50, minit=lcmm(fixed = value~1,
                                                                  random = ~ 1,
                                                                  ng = 1, 
                                                                  idiag = TRUE, 
                                                                  data = data.frame(data_df), subject = "index"))

mLF3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 3,nwg=TRUE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 3,nwg=TRUE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 3,nwg=FALSE,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 3,nwg=FALSE,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = FALSE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 3,nwg=FALSE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 3,nwg=FALSE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 
mLF3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 3,nwg=TRUE,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                       random = ~ 1,
                                                                       ng = 1, 
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index")) 
mLF3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 3,nwg=TRUE,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"),
                                   rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                   random = ~ 1,
                                                                   ng = 1, 
                                                                   idiag = TRUE, 
                                                                   data = data.frame(data_df), subject = "index")) 

mLFR3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 3,nwg=TRUE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 3,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFR3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 3,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 3,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 3,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 3,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFR3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1,
                   random = ~ 1+MPAS,
                   ng = 3,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B= lcmm(fixed = value~1+MPAS,
                                                                         random = ~ 1+MPAS,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mLFR3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1,
                                         random = ~ 1+MPAS,
                                         ng = 3,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1+MPAS,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 



mLFM3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 3,nwg=TRUE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 3,nwg=TRUE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 

mLFM3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 3,nwg=FALSE,
                   idiag = FALSE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = FALSE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 3,nwg=FALSE,
                                         idiag = FALSE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = FALSE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 3,nwg=FALSE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 3,nwg=FALSE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 
mLFM3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                   mixture = ~ 1+MPAS,
                   random = ~ 1,
                   ng = 3,nwg=TRUE,
                   idiag = TRUE, 
                   data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS,
                                                                        random = ~ 1,
                                                                        ng = 1,
                                                                        idiag = TRUE, 
                                                                        data = data.frame(data_df), subject = "index"))

mLFM3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                         mixture = ~ 1+MPAS,
                                         random = ~ 1,
                                         ng = 3,nwg=TRUE,
                                         idiag = TRUE, 
                                         data = data.frame(data_df), subject = "index"),
                                    rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                    random = ~ 1,
                                                                    ng = 1, 
                                                                    idiag = TRUE, 
                                                                    data = data.frame(data_df), subject = "index")) 


mLFRM3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mLFRM3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS,
                    mixture = ~ 1+MPAS,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS,
                                                                          random = ~ 1+MPAS,
                                                                          ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index")) 
mLFRM3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS,
                                          mixture = ~ 1+MPAS,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS,
                                                                                                                          random = ~ 1+MPAS,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 


mQF3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 3,
                  idiag = FALSE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = FALSE, 
                                                                       data = data.frame(data_df), subject = "index") )
mQF3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 3,
                                        idiag = FALSE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = FALSE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQF3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                  mixture = ~ 1,
                  random = ~ 1,
                  ng = 3,
                  idiag = TRUE, 
                  data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                       random = ~ 1,
                                                                       ng = 1,
                                                                       idiag = TRUE, 
                                                                       data = data.frame(data_df), subject = "index") )

mQF3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                        mixture = ~ 1,
                                        random = ~ 1,
                                        ng = 3,
                                        idiag = TRUE, 
                                        data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                        random = ~ 1,
                                                                                                                        ng = 1,
                                                                                                                        idiag = TRUE, 
                                                                                                                        data = data.frame(data_df), subject = "index") )


mQFLR3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = FALSE, 
                                                                          data = data.frame(data_df), subject = "index") )

mQFLR3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = FALSE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFLR3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )

mQFLR3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS,
                    ng = 3,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                          random = ~ 1+MPAS,ng = 1,
                                                                          idiag = TRUE, 
                                                                          data = data.frame(data_df), subject = "index") )
mQFLR3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS,
                                          ng = 3,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                           random = ~ 1+MPAS,ng = 1,
                                                                                                                           idiag = TRUE, 
                                                                                                                           data = data.frame(data_df), subject = "index") )


mQFQR3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 3,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 


mQFQR3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 3,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQR3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 3,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 
mQFQR3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 3,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 3,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 3,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQR3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1,
                    random = ~ 1+MPAS+I(MPAS^2),
                    ng = 3,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1+MPAS+I(MPAS^2),
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQR3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1,
                                          random = ~ 1+MPAS+I(MPAS^2),
                                          ng = 3,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 3,nwg=TRUE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 3,nwg=TRUE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQM3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 3,nwg=FALSE,
                    idiag = FALSE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = FALSE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 3,nwg=FALSE,
                                          idiag = FALSE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = FALSE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 3,nwg=FALSE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 3,nwg=FALSE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 

mQFQM3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                    mixture = ~ 1+MPAS+I(MPAS^2),
                    random = ~ 1,
                    ng = 3,nwg=TRUE,
                    idiag = TRUE, 
                    data = data.frame(data_df), subject = "index",B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                         random = ~ 1,
                                                                         ng = 1,
                                                                         idiag = TRUE, 
                                                                         data = data.frame(data_df), subject = "index")) 

mQFQM3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                          mixture = ~ 1+MPAS+I(MPAS^2),
                                          random = ~ 1,
                                          ng = 3,nwg=TRUE,
                                          idiag = TRUE, 
                                          data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                          random = ~ 1,
                                                                                                                          ng = 1,
                                                                                                                          idiag = TRUE, 
                                                                                                                          data = data.frame(data_df), subject = "index")) 



mQFQMLR3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 3,nwg=TRUE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 

mQFQMLR3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 3,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 3,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = FALSE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 3,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 




mQFQMLR3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 3,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 3,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, 
                                                                                                                            data = data.frame(data_df), subject = "index")) 


mQFQMLR3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS,
                      ng = 3,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                            random = ~ 1+MPAS,
                                                                            ng = 1,
                                                                            idiag = TRUE, 
                                                                            data = data.frame(data_df), subject = "index")) 
mQFQMLR3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS,
                                            ng = 3,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS,
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR3tf_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 3,nwg=TRUE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR3tf_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 3,nwg=TRUE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))


mQFQMQR3ff_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 3,nwg=FALSE,
                      idiag = FALSE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = FALSE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR3ff_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 3,nwg=FALSE,
                                            idiag = FALSE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = FALSE, data = data.frame(data_df), subject = "index"))

mQFQMQR3ft_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 3,nwg=FALSE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))

mQFQMQR3ft_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 3,nwg=FALSE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

mQFQMQR3tt_nr_MPAS <- lcmm(fixed = value~1+MPAS+I(MPAS^2),
                      mixture = ~ 1+MPAS+I(MPAS^2),
                      random = ~ 1+MPAS+I(MPAS^2),
                      ng = 3,nwg=TRUE,
                      idiag = TRUE, 
                      data = data.frame(data_df), subject = "index", B= lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                             random = ~ 1+MPAS+I(MPAS^2),
                                                                             ng = 1,
                                                                             idiag = TRUE, 
                                                                             data = data.frame(data_df), subject = "index"))


mQFQMQR3tt_nr_gridsearch_MPAS <- gridsearch(lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                            mixture = ~ 1+MPAS+I(MPAS^2),
                                            random = ~ 1+MPAS+I(MPAS^2),
                                            ng = 3,nwg=TRUE,
                                            idiag = TRUE, 
                                            data = data.frame(data_df), subject = "index"), rep=100, maxiter=50, minit=lcmm(fixed = value~1+MPAS+I(MPAS^2),
                                                                                                                            random = ~ 1+MPAS+I(MPAS^2),
                                                                                                                            ng = 1,
                                                                                                                            idiag = TRUE, data = data.frame(data_df), subject = "index"))

summarytable(m03tf_nr_MPAS,m03tf_nr_gridsearch_MPAS,m03ff_nr_MPAS,m03ff_nr_gridsearch_MPAS,m03ft_nr_MPAS,m03ft_nr_gridsearch_MPAS,m03tt_nr_MPAS,m03tt_nr_gridsearch_MPAS,
             mLF3tf_nr_MPAS,mLF3tf_nr_gridsearch_MPAS,mLF3ff_nr_MPAS,mLF3ff_nr_gridsearch_MPAS,mLF3ft_nr_MPAS,mLF3ft_nr_gridsearch_MPAS,mLF3tt_nr_MPAS,mLF3tt_nr_gridsearch_MPAS,
             mLFR3tf_nr_MPAS,mLFR3tf_nr_gridsearch_MPAS,mLFR3ff_nr_MPAS,mLFR3ff_nr_gridsearch_MPAS,mLFR3ft_nr_MPAS,mLFR3ft_nr_gridsearch_MPAS,mLFR3tt_nr_MPAS,mLFR3tt_nr_gridsearch_MPAS,
             mLFM3tf_nr_MPAS,mLFM3tf_nr_gridsearch_MPAS,mLFM3ff_nr_MPAS,mLFM3ff_nr_gridsearch_MPAS,mLFM3ft_nr_MPAS,mLFM3ft_nr_gridsearch_MPAS,mLFM3tt_nr_MPAS,mLFM3tt_nr_gridsearch_MPAS,
             mLFRM3tf_nr_MPAS,mLFRM3tf_nr_gridsearch_MPAS,mLFRM3ff_nr_MPAS,mLFRM3ff_nr_gridsearch_MPAS,mLFRM3ft_nr_MPAS,mLFRM3ft_nr_gridsearch_MPAS,mLFRM3tt_nr_MPAS,mLFRM3tt_nr_gridsearch_MPAS,
             mQF3tf_nr_MPAS,mQF3tf_nr_gridsearch_MPAS,mQF3ft_nr_MPAS,mQF3ft_nr_gridsearch_MPAS,
             mQFLR3tf_nr_MPAS,mQFLR3tf_nr_gridsearch_MPAS,mQFLR3ff_nr_MPAS,mQFLR3ff_nr_gridsearch_MPAS,mQFLR3ft_nr_MPAS,mQFLR3ft_nr_gridsearch_MPAS,mQFLR3tt_nr_MPAS,mQFLR3tt_nr_gridsearch_MPAS,
             mQFQR3tf_nr_MPAS,mQFQR3tf_nr_gridsearch_MPAS,mQFQR3ff_nr_MPAS,mQFQR3ff_nr_gridsearch_MPAS,mQFQR3ft_nr_MPAS,mQFQR3ft_nr_gridsearch_MPAS,mQFQR3tt_nr_MPAS,mQFQR3tt_nr_gridsearch_MPAS,
             mQFQM3tf_nr_MPAS,mQFQM3tf_nr_gridsearch_MPAS,mQFQM3ff_nr_MPAS,mQFQM3ff_nr_gridsearch_MPAS,mQFQM3ft_nr_MPAS,mQFQM3ft_nr_gridsearch_MPAS,mQFQM3tt_nr_MPAS,mQFQM3tt_nr_gridsearch_MPAS,
             mQFQMLR3tf_nr_MPAS,mQFQMLR3tf_nr_gridsearch_MPAS,mQFQMLR3ff_nr_MPAS,mQFQMLR3ff_nr_gridsearch_MPAS,mQFQMLR3ft_nr_MPAS,mQFQMLR3ft_nr_gridsearch_MPAS,mQFQMLR3tt_nr_MPAS,mQFQMLR3tt_nr_gridsearch_MPAS,
             mQFQMQR3tf_nr_MPAS,mQFQMQR3tf_nr_gridsearch_MPAS,mQFQMQR3ff_nr_MPAS,mQFQMQR3ff_nr_gridsearch_MPAS,mQFQMQR3ft_nr_MPAS,mQFQMQR3ft_nr_gridsearch_MPAS,mQFQMQR3tt_nr_MPAS,mQFQMQR3tt_nr_gridsearch_MPAS, 
             which = c("G", "loglik", "conv", "npm", "AIC", "BIC", "SABIC", "entropy", "%class"))->t3_MPAS
kable(t3_MPAS, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  cat(., file = "m3_MPAS.html")